#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

"""

ABOUT: This is the main entry for the pipeline.
REQUIRES:
  - python>=3.6
  - snakemake   (recommended>=6.0.0)
  - singularity (recommended==latest)
DISCLAIMER:
                    PUBLIC DOMAIN NOTICE
        NIAID Collaborative Bioinformatics Resource (NCBR)
   National Institute of Allergy and Infectious Diseases (NIAID)
This software/database is a "United  States Government Work" under
the terms of the United  States Copyright Act.  It was written as
part of the author's official duties as a United States Government
employee and thus cannot be copyrighted. This software is freely
available to the public for use.
Although all  reasonable  efforts have been taken  to ensure  the
accuracy and reliability of the software and data, NCBR do not and
cannot warrant the performance or results that may  be obtained by
using this software or data. NCBR and NIH disclaim all warranties,
express  or  implied,  including   warranties   of   performance,
merchantability or fitness for any particular purpose.
Please cite the author and NIH resources like the "Biowulf Cluster"
in any work or product based on this material.
USAGE:
  $ chrom-seek <command> [OPTIONS]
EXAMPLE:
  $ chrom-seek run -h

"""

# Python standard library
from __future__ import print_function
import sys, os, subprocess, re, json, textwrap

# 3rd party imports from pypi
import argparse  # potential python3 3rd party package, added in python/3.5

# Local imports
from src import version
from src.run import init, setup, bind, dryrun, runner
from src.files import peakcalls, contrasts, validate_custom_genome
from src.shells import bash
from src.utils import (
    Colors,
    err,
    exists,
    fatal,
    permissions,
    check_cache,
    require,
    valid_trigger,
)


# Pipeline Metadata
__version__ = version
__authors__ = "Skyler Kuhn, Tovah Markowitz"
__email__ = "skyler.kuhn@nih.gov, tovah.markowitz@nih.gov"
__home__ = os.path.dirname(os.path.abspath(__file__))
_name = os.path.basename(sys.argv[0])
_description = "An awesome set of epigenetic pipelines"


def unlock(sub_args):
    """Unlocks a previous runs output directory. If snakemake fails ungracefully,
    it maybe required to unlock the working directory before proceeding again.
    This is rare but it does occasionally happen. Maybe worth add a --force
    option to delete the '.snakemake/' directory in the future.
    @param sub_args <parser.parse_args() object>:
        Parsed arguments for unlock sub-command
    """
    print("Unlocking the pipeline's output directory...")
    outdir = sub_args.output

    try:
        unlock_output = subprocess.check_output(
            ["snakemake", "--unlock", "--cores", "1", "--configfile=config.json"],
            cwd=outdir,
            stderr=subprocess.STDOUT,
        )
    except subprocess.CalledProcessError as e:
        # Unlocking process returned a non-zero exit code
        sys.exit("{}\n{}".format(e, e.output))

    print("Successfully unlocked the pipeline's working directory!")


def run(sub_args):
    """Initialize, setup, and run the pipeline.
    Calls initialize() to create output directory and copy over pipeline resources,
    setup() to create the pipeline config file, dryrun() to ensure their are no issues
    before running the pipeline, and finally run() to execute the Snakemake workflow.
    @param sub_args <parser.parse_args() object>:
        Parsed arguments for run sub-command
    """
    # Step 0. Check for required dependencies
    # The pipelines has only two requirements:
    # snakemake and singularity
    require(["snakemake", "singularity"], ["snakemake", "singularity"])
    c = Colors()

    # Step 1. Initialize working directory,
    # copy over required resources to run
    # the pipeline
    git_repo = __home__
    input_files = init(
        repo_path=git_repo, output_path=sub_args.output, links=sub_args.input
    )

    # Step 2. Setup pipeline for execution,
    # dynamically create config.json config
    # file from user inputs and base config
    # templates
    config = setup(
        sub_args, ifiles=input_files, repo_path=git_repo, output_path=sub_args.output
    )

    # Step 3. Resolve docker/singularity bind
    # paths from the config file.
    bindpaths = bind(sub_args, config=config)

    config["bindpaths"] = bindpaths

    # Add peakcall.tsv and contrasts.tsv file
    # information, peakcall.tsv file defines
    # relationships between ChIP samples and
    # their inputs AND it defines its group.
    # The contrast.tsv file defines comparsions
    # to be made with groups of samples.
    # Add peakcall information to config.json
    chip2input, groups, blocks = peakcalls(sub_args.peakcall, assay=sub_args.assay.lower())
    # Check if optional Block column, if blocking
    # information exists, then each row must have
    # a value, error out if missing values (i.e. None)
    if (
        len(blocks.values()) != list(blocks.values()).count(None)
        and None in blocks.values()
    ):
        missing_blocks = [k for k, v in blocks.items() if v is None]
        # Missing fields in blocks column
        err(
            "{}{}Error: peakcall file contains missing Block information for these samples: {}".format(
                c.bg_red, c.white, c.end
            )
        )
        fatal("\t └── {}".format(missing_blocks))

    # Adding peakcall information to projects
    chips_samples = list(chip2input.keys())
    input_samples = chip2input
    config["project"]["peaks"] = {}
    config["project"]["peaks"]["chips"] = chips_samples
    config["project"]["peaks"]["inputs"] = input_samples
    config["project"]["groups"] = groups
    config["project"]["blocks"] = blocks
    # Running some basic vaildation, checking
    # that samples defined in the peakcall
    # file have a corresponding FastQ file,
    # this will prevent/catch dryrun errors
    # before they happen.
    peakcall_samples = list(set(chips_samples))
    if set(input_samples.values()) not in ({''}, {None}):
        peakcall_samples = peakcall_samples + list(set(input_samples.values()))
    peakcall_samples = [s for s in peakcall_samples if isinstance(s, str) and s.strip()]
    missing_inputs = []
    for s in peakcall_samples:
        if s not in config["samples"]:
            # Collect all missing input fastq files
            # that are listed in the peakcall file
            missing_inputs.append(s)

    if missing_inputs:
        # Report missing FastQ files that
        # were not provided and display a
        # helpful message to fix problem
        err(
            "{}{}Error: peakcall file contains the following samples with missing FastQ files! {}".format(
                c.bg_red, c.white, c.end
            )
        )
        fatal("\t └── {}".format(missing_inputs))

    # Sanity checks for cfchip pipeline
    #  1. cfchip only supports hg19
    #  2. cfchip requires Input samples in peakcall file
    if sub_args.assay.lower() == "cfchip":
        chip_missing_input = {
            c: i for c, i in config["project"]["peaks"]["inputs"].items() if not i
        }
        if sub_args.genome != "hg19":
            err(
                'Error: Unsupported reference genome, "{0}", for pipeline: "cfchip"'.format(
                    sub_args.genome
                )
            )
            fatal(
                '  └── The cfchip pipeline only runs with the following reference genome : "hg19"'
            )

        if chip_missing_input:
            err("Error: Missing input for chip sample in peakcall file!")
            err("  └── Input samples are required for the cfchip pipeline.")
            fatal(
                "  └── Please provide inputs for the following chips: {}".format(
                    list(chip_missing_input.keys())
                )
            )

    # Sanity checks for atac pipeline
    # ATAC pipeline does not use input samples
    if sub_args.assay.lower() == "atac":
        chip_with_input = {
            c: i for c, i in config["project"]["peaks"]["inputs"].items() if i
        }
        for c, i in chip_with_input.items():
            err(
                'Warning: Provided input "{}" to sample "{}" when using the ATAC-seq pipeline!'.format(
                    i, c
                ),
                "ATAC-seq does not use input samples, skipping over provided input.",
            )

    # Add contrast information to config.json
    config["project"]["contrast"] = {}
    if sub_args.contrasts:
        user_defined_groups = list(groups.keys())
        comparsions = contrasts(sub_args.contrasts, user_defined_groups)
        config["project"]["contrast"] = comparsions

    # Step 4. Save config to output directory
    with open(os.path.join(sub_args.output, "config.json"), "w") as fh:
        json.dump(config, fh, indent=4, sort_keys=True)

    if sub_args.genome.endswith(".json"):
        parsed_genome = validate_custom_genome(sub_args.genome)["references"]
        genome_k = list(parsed_genome.keys())[0]
        supported_pipelines = parsed_genome[genome_k]["SUPPORTED_PIPELINES"]
    else:
        supported_pipelines = config["references"][sub_args.genome][
            "SUPPORTED_PIPELINES"
        ]

    if sub_args.assay not in supported_pipelines:
        fatal(
            "\nWarning: {} assay is not supported for {} genome".format(
                sub_args.assay, sub_args.genome
            )
        )

    # Optional Step: Dry-run pipeline
    if sub_args.dry_run:
        # Dryrun pipeline
        dryrun_output = dryrun(
            outdir=sub_args.output
        )  # python3 returns byte-string representation
        print(
            "\nDry-running {} pipeline:\n{}".format(
                _name, dryrun_output.decode("utf-8")
            )
        )
        sys.exit(0)

    # Step 5. Orchestrate pipeline execution,
    # run pipeline in locally on a compute node
    # for debugging purposes or submit the master
    # job to the job scheduler, SLURM, and create
    # logging file
    if not exists(os.path.join(sub_args.output, "logfiles")):
        # Create directory for logfiles
        os.makedirs(os.path.join(sub_args.output, "logfiles"))
    if sub_args.mode == "local":
        log = os.path.join(sub_args.output, "logfiles", "snakemake.log")
    else:
        log = os.path.join(sub_args.output, "logfiles", "master.log")
    logfh = open(log, "w")
    triggers = sub_args.triggers if sub_args.triggers else None
    mjob = runner(
        mode=sub_args.mode,
        outdir=sub_args.output,
        # additional_bind_paths = all_bind_paths,
        alt_cache=sub_args.singularity_cache,
        threads=int(sub_args.threads),
        jobname=sub_args.job_name,
        submission_script=os.path.join(__home__, "src", "run.sh"),
        logger=logfh,
        additional_bind_paths=",".join(bindpaths),
        tmp_dir=sub_args.tmp_dir,
        triggers=triggers,
    )

    # Step 6. Wait for subprocess to complete,
    # this is blocking and not asynchronous
    if not sub_args.silent:
        print("\nRunning {} pipeline in '{}' mode...".format(_name, sub_args.mode))
    mjob.wait()
    logfh.close()

    # Step 7. Relay information about submission
    # of the master job or the exit code of the
    # pipeline that ran in local mode
    if sub_args.mode == "local":
        if int(mjob.returncode) == 0:
            print("{} pipeline has successfully completed".format(_name))
        else:
            fatal(
                "{} pipeline failed. Please see {} for more information.".format(
                    _name, os.path.join(sub_args.output, "logfiles", "snakemake.log")
                )
            )
    elif sub_args.mode == "slurm":
        jobid = (
            open(os.path.join(sub_args.output, "logfiles", "mjobid.log")).read().strip()
        )
        if not sub_args.silent:
            if int(mjob.returncode) == 0:
                print("Successfully submitted master job: ", end="")
            else:
                fatal("Error occurred when submitting the master job.")
        print(jobid)


def cache(sub_args):
    """Caches remote software containers stored on DockerHub.
    Local SIFs will be created from images defined in 'config/containers/images.json'.
    @param sub_args <parser.parse_args() object>:
        Parsed arguments for unlock sub-command
    """
    # Check for dependencies
    require(["singularity"], ["singularity"])

    sif_cache = sub_args.sif_cache
    # Get absolute PATH to templates in exome-seek git repo
    repo_path = os.path.dirname(os.path.abspath(__file__))
    images = os.path.join(repo_path, "config", "containers.json")

    # Create image cache
    if not exists(sif_cache):
        # Pipeline output directory does not exist on filesystem
        os.makedirs(sif_cache)
    elif exists(sif_cache) and os.path.isfile(sif_cache):
        # Provided Path for pipeline output directory exists as file
        raise OSError(
            """\n\tFatal: Failed to create provided sif cache directory!
        User provided --sif-cache PATH already exists on the filesystem as a file.
        Please {} cache again with a different --sif-cache PATH.
        """.format(
                _name
            )
        )

    # Check if local SIFs already exist on the filesystem
    with open(images, "r") as fh:
        data = json.load(fh)

    pull = []
    for image, uri in data["images"].items():
        sif = os.path.join(
            sif_cache, "{}.sif".format(os.path.basename(uri).replace(":", "_"))
        )
        if not exists(sif):
            # If local sif does not exist on in cache, print warning
            # and default to pulling from URI in config/containers.json
            print('Image will be pulled from "{}".'.format(uri), file=sys.stderr)
            pull.append(uri)

    if not pull:
        # Nothing to do!
        print("Singularity image cache is already up to update!")
    else:
        # There are image(s) that need to be pulled
        if not sub_args.dry_run:
            # container cache script: src/cache.sh
            # Quote user provided values to avoid shell injections
            username = os.environ.get("USER", os.environ.get("USERNAME"))
            exitcode = bash(
                str(os.path.join(repo_path, "src", "cache.sh"))
                + " local "
                + " -s '{}' ".format(sif_cache)
                + " -i '{}' ".format(",".join(pull))
                + " -t '{0}/{1}/.singularity/' ".format(sif_cache, username)
            )
            # Check exitcode of caching script
            if exitcode != 0:
                fatal("Fatal: Failed to pull all containers. Please try again!")
            print("Done: sucessfully pulled all software containers!")


def parsed_arguments(name, description):
    """Parses user-provided command-line arguments. Requires argparse and textwrap
    package. argparse was added to standard lib in python 3.5 and textwrap was added
    in python 3.5. To create custom help formatting for subparsers a docstring is
    used create the help message for required options. argparse does not support named
    subparser groups, which is normally what would be used to accomphish this reformatting.
    As so, the help message for require options must be suppressed. If a new required arg
    is added to a subparser, it must be added to the docstring and the usage statement
    also must be updated.
    @param name <str>:
        Name of the pipeline or command-line tool
    @param description <str>:
        Short description of pipeline or command-line tool
    """
    # Add styled name and description
    c = Colors
    styled_name = "{0}{1}{2}chrom-seek{3}".format(c.bold, c.bg_black, c.cyan, c.end)
    description = "{0}{1}{2}".format(c.bold, description, c.end)

    # Create a top-level parser
    parser = argparse.ArgumentParser(
        description="{}: {}".format(styled_name, description)
    )

    # Adding Verison information
    parser.add_argument(
        "--version", action="version", version="%(prog)s {}".format(__version__)
    )

    # Create sub-command parser
    subparsers = parser.add_subparsers(help="List of available sub-commands")

    # Sub-parser for the "run" sub-command
    # Grouped sub-parser arguments are currently
    # not supported: https://bugs.python.org/issue9341
    # Here is a work around to create more useful help message for named
    # options that are required! Please note: if a required arg is added the
    # description below should be updated (i.e. update usage and add new option)
    required_run_options = textwrap.dedent(
        """\
        {0}: {1}

        {3}{4}Synopsis:{5}
          $ {2} run [--help] \\
                [--dry-run] [--job-name JOB_NAME] [--mode {{slurm,local}}] \\
                [--sif-cache SIF_CACHE] [--singularity-cache SINGULARITY_CACHE] \\
                [--silent] [--threads THREADS] [--tmp-dir TMP_DIR] \\
                [--contrasts CONTRASTS] \\
                --assay {{cfChIP,ChIP,ATAC,cutnrun}} \\
                --genome GENOME \\
                --input INPUT [INPUT ...] \\
                --output OUTPUT \\
                --peakcall PEAKCALL

        Optional arguments are shown in square brackets above.

        {3}{4}Description:{5}
          To run an available pipeline with your data raw data, please provide a space 
        seperated list of FastQ (globbing is supported), an output directory to store 
        results, a reference genome for alignment and annotation, an assay type to 
        call a specific data-processing pipeline, and a peakcall file to pair samples
        to their respective groups.

        {3}{4}Required arguments:{5}
          --assay {{cfChIP,ChIP,ATAC,cutnrun}}
                                Assay type or data-processing pipeline. This option
                                defines which pipeline will be run. chrom-seek supports
                                the processing of bulk ChIP-seq (ChIP), cell-free DNA 
                                ChIP-seq (cfChIP), ATAC-seq (ATAC) samples, and
                                CUT & RUN or CUT & TAG (cutnrun). Please select from 
                                from one of the following data-processing pipelines:
                                    • ChIP
                                    • cfChIP
                                    • ATAC
                                    • cutnrun
                                  Example: --assay ChIP
          --genome GENOME       
                                Reference genome. This option defines the reference
                                genome of the samples for alignment and annotation.
                                There are prebuilt reference files for human, mouse, 
                                and rhesus samples. Select one of the following options:
                                    • hg19
                                    • hg38
                                    • mm10
                                    • mm39
                                    • rheMac10
                                  Example: --genome hg19
          --input INPUT [INPUT ...]
                                Input FastQ file(s) to process. The pipeline does NOT
                                support single-end data. FastQ files for one or more  
                                samples can be provided. Multiple input FastQ files
                                should be seperated by a space. Globbing for multiple
                                file is also supported.
                                  Example: --input .tests/*.R?.fastq.gz
          --output OUTPUT
                                Path to an output directory. This location is where
                                the pipeline will create all of its output files, also
                                known as the pipeline's working directory. If the user
                                provided working directory has not been initialized,
                                it will be created automatically.
                                  Example: --output /data/$USER/output
          --peakcall PEAKCALL
                                Peakcall file. This tab delimited file is used to pair
                                each CHiP/ATAC/cutnrun/cfCHiP sample to its InputControl
                                sample AND to assign any groups that are associated with 
                                said sample. 
                                
                                Please note that multiple groups can be assigned to a 
                                given sample. 
                                
                                Group information is used to setup comparsions within 
                                groups of samples. 
                                
                                This file consists of two required columns and two optional 
                                columns:
                                  • Required: Sample, Group
                                  • Optional: Blocks, InputControl

                                The base name of each library should be listed in the `Sample` 
                                and `InputControl` columns. The base name of a given sample 
                                can be determined by removing its file extension from the 
                                sample's R1 FastQ file, example:
                                  • WT_S4.R1.fastq.gz becomes WT_S4 in the peakcall file.
                               
                                  Contents of example peakcalls file:
                                    Sample	InputControl	Group   Block
                                    WT_S1	IN_S1	        G1,G3   S1
                                    WT_S2	IN_S2	        G1,G3   S1
                                    WT_S3	IN_S3	        G1      S2
                                    WT_S4	IN_S4	        G2,G4   S2
                                    WT_S5	IN_S5	        G2,G4   S3
                                    WT_S6	IN_S6	        G2      S3
                                  Example: --peakcall /data/$USER/peakcall.tsv 

        {3}{4}Analysis options:{5}
        {6}@Differential Binding/Accessibility{5} 
          --contrasts CONTRASTS
                                Contrasts file. This tab delimited file is used to setup
                                comparisons within different groups of samples. Please 
                                see the --peakcall option for more information about 
                                how to define groups within a set of samples. This file
                                consists of two columns containing the names of each 
                                group to compare. The names defined in this file must 
                                also exist in the peakcall file.
                                  Contents of example contrasts file:
                                    G2  G1
                                    G4  G1
                                    G4  G3
                                  Example: --contrasts /data/$USER/contrasts.tsv 

        {3}{4}Orchestration options:{5}
          --mode {{slurm,local}}  
                                Method of execution. Defines the mode of execution. 
                                Vaild options for this mode include: local or slurm. 
                                Additional modes of exection are coming soon, default:  
                                slurm.
                                Here is a brief description of each mode:
                                   • local: uses local method of execution. local runs 
                                will run serially on compute instance. This is useful 
                                for testing, debugging, or when a users does not have
                                access to a  high  performance  computing environment.
                                If this option is not provided, it will default to a 
                                slurm mode of execution. 
                                   • slurm: uses slurm execution backend. This method 
                                will submit jobs to a  cluster  using sbatch. It is 
                                recommended running the pipeline in this mode as it 
                                will be significantly faster. 
                                  Example: --mode slurm
          --job-name JOB_NAME   
                                Overrides the name of the pipeline's master job. When 
                                submitting the pipeline to a jobscheduler, this option
                                overrides the default name of the master job. This can 
                                be useful for tracking the progress or status of a run, 
                                default: pl:{2}.
                                  Example: --job-name {2}_03-14.1592
          --dry-run             
                                Does not execute anything. Only displays what steps in
                                the pipeline remain or will be run.
                                  Example: --dry-run
          --silent              
                                Silence standard output. This will reduces the amount 
                                of information displayed to standard  output  when the 
                                master job is submitted to the job scheduler. Only the 
                                job id of the master job is returned.
                                  Example: --silent
          --singularity-cache SINGULARITY_CACHE
                                Overrides the $SINGULARITY_CACHEDIR variable. Images
                                from remote registries are cached locally on the file
                                system. By default, the singularity cache is set to:
                                '/path/to/output/directory/.singularity/'. Please note
                                that this cache cannot be shared across users.
                                  Example: --singularity-cache /data/$USER
          --sif-cache SIF_CACHE
                                Path where a local cache of SIFs are stored. This cache
                                can be shared across users if permissions are properly
                                setup. If a SIF does not exist in the SIF cache, the
                                image will be pulled from Dockerhub. {2} cache
                                sub command can be used to create a local SIF cache. 
                                Please see {2} cache for more information.
                                   Example: --sif-cache /data/$USER/sifs/
          --tmp-dir TMP_DIR     
                                Path on the file system for writing temporary output 
                                files. By default, the temporary directory is set to 
                                '/lscratch/$SLURM_JOB_ID' for backwards compatibility 
                                with the NIH's Biowulf cluster; however, if you are 
                                running the pipeline on another cluster, this option 
                                will need to be specified. Ideally, this path should 
                                point to a dedicated location on the filesystem for 
                                writing tmp files. On many systems, this location is 
                                set to somewhere in /scratch. If you need to inject a 
                                variable into this string that should NOT be expanded, 
                                please quote this options value in single quotes. 
                                  Example: --tmp-dir '/scratch/$USER/'
          --threads THREADS     
                                Max number of threads for local processes. It is
                                recommended setting this vaule to the maximum number 
                                of CPUs available on the host machine, default: 2.
                                  Example: --threads: 16

          -t(--triggers) TRIGGER [TRIGGER ...]
                                Manual control of the snakemake rerun triggers.
                                Trigger values must be one or more of:
                                  • mtime
                                  • code
                                  • software-env
                                  • input
                                  • params
                                See https://snakemake.readthedocs.io/en/stable/executing/cli.html
                                for more details about snakemake rerun triggers.
                                Default (in prority order):
                                    params, mtime, code, software-env, input
        
        {3}{4}Misc Options:{5}
          -h, --help            Show usage information, help message, and exit.
                                  Example: --help
        """.format(
            styled_name, description, name, c.bold, c.url, c.end, c.italic
        )
    )

    # Display example usage in epilog
    run_epilog = textwrap.dedent(
        """\
        {2}{3}Example:{4}
          # Step 1.) Grab an interactive node,
          # do not run on head node!
          srun -N 1 -n 1 --time=1:00:00 --mem=8gb  --cpus-per-task=2 --pty bash
          module purge
          module load singularity snakemake

          # Step 2A.) Dry-run the pipeline
          ./{0} run --assay ChIP \\
                         --genome hg19 \\
                         --input .tests/*.R?.fastq.gz \\
                         --output /data/$USER/output \\
                         --peakcall .tests/peakcall.tsv \\
                         --mode slurm \\
                         --dry-run

          # Step 2B.) Run the {0} pipeline
          # The slurm mode will submit jobs to 
          # the cluster. It is recommended running 
          # the pipeline in this mode.
          ./{0} run --assay ChIP \\
                         --genome hg19 \\
                         --input .tests/*.R?.fastq.gz \\
                         --output /data/$USER/output \\
                         --peakcall .tests/peakcall.tsv \\
                         --mode slurm 

        {2}{3}Version:{4}
          {1}
        """.format(
            name, __version__, c.bold, c.url, c.end
        )
    )

    # Supressing help message of required args to overcome no sub-parser named groups
    subparser_run = subparsers.add_parser(
        "run",
        help="Run the {} pipeline with input files.".format(name),
        usage=argparse.SUPPRESS,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=required_run_options,
        epilog=run_epilog,
        add_help=False,
    )

    # Required Arguments
    # Data-procssing pipeline
    subparser_run.add_argument(
        "--assay",
        type=lambda option: str.lower(option),
        required=True,
        choices=["chip", "cfchip", "atac", "cutnrun"],
        help=argparse.SUPPRESS,
    )

    def valid_genome(genome):
        valid_choices = ["hg19", "hg38", "mm10", "mm39", "rheMac10"]
        if genome in valid_choices:
            return genome
        if os.path.exists(genome) and genome.endswith(".json"):
            return genome
        raise argparse.ArgumentTypeError(
            "Unsupported genome, please use one of:\n"
            + '\t"hg19", "hg38", "mm10", "mm39", "rheMac10"\n'
            + "Or a valid json file ending with .json"
        )

    # Reference genome
    subparser_run.add_argument(
        "--genome",
        required=True,
        type=str,
        help=argparse.SUPPRESS,
    )

    # Input FastQ files
    subparser_run.add_argument(
        "--input",
        # Check if the file exists and if it is readable
        type=lambda file: permissions(parser, file, os.R_OK),
        required=True,
        nargs="+",
        help=argparse.SUPPRESS,
    )

    # Output Directory, i.e
    # working directory
    subparser_run.add_argument(
        "--output",
        type=lambda option: os.path.abspath(os.path.expanduser(option)),
        required=True,
        help=argparse.SUPPRESS,
    )

    # Peakcall file to match
    # ChIP and Input samples,
    # Samples to Groups, and
    # Samples to Blocking
    # factors in model.
    subparser_run.add_argument(
        "--peakcall",
        # Check if the file exists and if it is readable
        type=lambda file: permissions(parser, file, os.R_OK),
        required=True,
        help=argparse.SUPPRESS,
    )

    # Optional Arguments
    # Add custom help message
    subparser_run.add_argument("-h", "--help", action="help", help=argparse.SUPPRESS)

    # Analysis options
    # Contrasts file for differential
    # binding/accessibility analysis
    subparser_run.add_argument(
        "--contrasts",
        # Check if the file exists and if it is readable
        type=lambda file: permissions(parser, file, os.R_OK),
        required=False,
        default=None,
        help=argparse.SUPPRESS,
    )

    # Orchestration Options
    # Execution Method, run locally
    # on a compute node or submit to
    # a supported job scheduler, etc.
    subparser_run.add_argument(
        "--mode",
        type=str,
        required=False,
        default="slurm",
        choices=["slurm", "local"],
        help=argparse.SUPPRESS,
    )

    # Name of master job
    subparser_run.add_argument(
        "--job-name",
        type=str,
        required=False,
        default="pl:{}".format(name),
        help=argparse.SUPPRESS,
    )

    # Dry-run
    # Do not execute the workflow,
    # prints what steps remain
    subparser_run.add_argument(
        "--dry-run",
        action="store_true",
        required=False,
        default=False,
        help=argparse.SUPPRESS,
    )

    # Snakemake rerun triggers
    subparser_run.add_argument(
        "-t",
        "--triggers",
        type=valid_trigger,
        required=False,
        default=None,
        nargs="*",
        help=argparse.SUPPRESS,
    )

    # Silent output mode
    subparser_run.add_argument(
        "--silent",
        action="store_true",
        required=False,
        default=False,
        help=argparse.SUPPRESS,
    )

    # Singularity cache directory,
    # default uses output directory
    subparser_run.add_argument(
        "--singularity-cache",
        type=lambda option: check_cache(
            parser, os.path.abspath(os.path.expanduser(option))
        ),
        default=None,
        required=False,
        help=argparse.SUPPRESS,
    )

    # Local SIF cache directory,
    # default pull from Dockerhub
    subparser_run.add_argument(
        "--sif-cache",
        type=lambda option: os.path.abspath(os.path.expanduser(option)),
        required=False,
        help=argparse.SUPPRESS,
    )

    # Base directory to write
    # temporary/intermediate files
    subparser_run.add_argument(
        "--tmp-dir",
        type=str,
        required=False,
        default="/lscratch/$SLURM_JOB_ID/",
        help=argparse.SUPPRESS,
    )

    # Number of threads for the
    # pipeline's main proceess
    # This is only applicable for
    # local rules or when running
    # in local mode.
    subparser_run.add_argument(
        "--threads", type=int, required=False, default=2, help=argparse.SUPPRESS
    )

    # Sub-parser for the "unlock" sub-command
    # Grouped sub-parser arguments are currently
    # not supported: https://bugs.python.org/issue9341
    # Here is a work around to create more useful help message for named
    # options that are required! Please note: if a required arg is added the
    # description below should be updated (i.e. update usage and add new option)
    required_unlock_options = textwrap.dedent(
        """\
        {0}: {1}

        {3}{4}Synopsis:{5} 
          $ {2} unlock [-h] --output OUTPUT
    
        Optional arguments are shown in square brackets above.

        {3}{4}Description:{5}
          If the pipeline fails ungracefully, it maybe required to unlock
        the working directory before proceeding again. Please verify that 
        the pipeline is not running before running this command. If the 
        pipeline is still running, the workflow manager will report the 
        working directory is locked. This is normal behavior. Do NOT run 
        this command if the pipeline is still running.

        {3}{4}Required arguments:{5}
          --output OUTPUT       Path to a previous run's output directory
                                to unlock. This will remove a lock on the 
                                working directory. Please verify that the 
                                pipeline is not running before running 
                                this command.
                                  Example: --output /data/$USER/output

        {3}{4}Misc Options:{5}
          -h, --help            Show usage information, help message, 
                                and exit.
                                  Example: --help
        """.format(
            styled_name, description, name, c.bold, c.url, c.end
        )
    )

    # Display example usage in epilog
    unlock_epilog = textwrap.dedent(
        """\
        {2}{3}Example:{4}
          # Unlock output directory of pipeline
          {0} unlock --output /data/$USER/output

        {2}{3}Version:{4}
          {1}
        """.format(
            name, __version__, c.bold, c.url, c.end
        )
    )

    # Supressing help message of required args to overcome no sub-parser named groups
    subparser_unlock = subparsers.add_parser(
        "unlock",
        help="Unlocks a previous runs output directory.",
        usage=argparse.SUPPRESS,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=required_unlock_options,
        epilog=unlock_epilog,
        add_help=False,
    )

    # Required Arguments
    # Output Directory (analysis working directory)
    subparser_unlock.add_argument(
        "--output", type=str, required=True, help=argparse.SUPPRESS
    )

    # Add custom help message
    subparser_unlock.add_argument("-h", "--help", action="help", help=argparse.SUPPRESS)

    # Sub-parser for the "cache" sub-command
    # Grouped sub-parser arguments are
    # not supported: https://bugs.python.org/issue9341
    # Here is a work around to create more useful help message for named
    # options that are required! Please note: if a required arg is added the
    # description below should be updated (i.e. update usage and add new option)
    required_cache_options = textwrap.dedent(
        """\
        {0}: {1}

        {3}{4}Synopsis:{5} 
          $ {2} cache [-h] [--dry-run] --sif-cache SIF_CACHE

        Optional arguments are shown in square brackets above.

        {3}{4}Description:{5}
          Creates a local cache resources hosted on DockerHub or AWS S3.
        These resources are normally pulled onto the filesystem when the
        pipeline runs; however, due to network issues or DockerHub pull
        rate limits, it may make sense to pull the resources once so a
        shared cache can be created. It is worth noting that a singularity
        cache cannot normally be shared across users. Singularity strictly
        enforces that a cache is owned by the user. To get around this
        issue, the cache subcommand can be used to create local SIFs on
        the filesystem from images on DockerHub.

        {3}{4}Required arguments:{5}
          --sif-cache SIF_CACHE
                                Path where a local cache of SIFs will be 
                                stored. Images defined in containers.json
                                will be pulled into the local filesystem. 
                                The path provided to this option can be 
                                passed to the --sif-cache option of the
                                run sub command. Please see {2} 
                                run sub command for more information.
                                  Example: --sif-cache /data/$USER/cache
        
        {3}{4}Orchestration options:{5}
          --dry-run             Does not execute anything. Only displays 
                                what remote resources would be pulled.
                                  Example: --dry-run
    
        {3}{4}Misc Options:{5}
          -h, --help            Show usage information, help message, 
                                and exits.
                                  Example: --help
    
        """.format(
            styled_name, description, name, c.bold, c.url, c.end
        )
    )

    # Display example usage in epilog
    cache_epilog = textwrap.dedent(
        """\
        {2}{3}Example:{4}
          # Cache remote resources of pipeline
          {0} cache --sif-cache /data/$USER/cache
    
        {2}{3}Version:{4}
          {1}
        """.format(
            name, __version__, c.bold, c.url, c.end
        )
    )

    # Supressing help message of required args to overcome no sub-parser named groups
    subparser_cache = subparsers.add_parser(
        "cache",
        help="Cache remote resources locally.",
        usage=argparse.SUPPRESS,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=required_cache_options,
        epilog=cache_epilog,
        add_help=False,
    )

    # Required Arguments
    # Output Directory (analysis working directory)
    subparser_cache.add_argument(
        "--sif-cache",
        type=lambda option: os.path.abspath(os.path.expanduser(option)),
        required=True,
        help=argparse.SUPPRESS,
    )

    # Optional Arguments
    # Dry-run cache command (do not pull any remote resources)
    subparser_cache.add_argument(
        "--dry-run",
        action="store_true",
        required=False,
        default=False,
        help=argparse.SUPPRESS,
    )

    # Add custom help message
    subparser_cache.add_argument("-h", "--help", action="help", help=argparse.SUPPRESS)

    # Define handlers for each sub-parser
    subparser_run.set_defaults(func=run)
    subparser_unlock.set_defaults(func=unlock)
    subparser_cache.set_defaults(func=cache)

    # Parse command-line args
    args = parser.parse_args()
    return args


def main():
    # Sanity check for usage
    if len(sys.argv) == 1:
        # Nothing was provided
        fatal("Invalid usage: {} [-h] [--version] ...".format(_name))

    # Collect args for sub-command
    args = parsed_arguments(name=_name, description=_description)

    # Display version information
    err("{} ({})".format(_name, __version__))

    # Mediator method to call sub-command's set handler function
    args.func(args)


if __name__ == "__main__":
    main()
